sudo: false
language: node_js
cache:
  direcotories:
    - node_modules
script:
  - npm run lint
deploy:
  provider: npm
  email: "lexswed@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
after_success:
  - npm run semantic-release