language: node_js
script:
  - npm run lint
  - npm run publish
deploy:
  provider: npm
  email: "lexswed@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
after_success:
  - git config user.email "travis@travis.org"
  - git config user.name "travis"
  - git add *
  - git commit --allow-empty -m "Automated build \#$TRAVIS_BUILD_NUMBER"
  - git push origin master