language: node_js
script:
  - npm run lint
deploy:
  provider: npm
  email: "lexswed@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
after_success:
  - npm run publish
  - git config user.email "travis@travis.org"
  - git config user.name "travis"
  - git add *
  - git commit --allow-empty -m "Automated build #$TRAVIS_BUILD_NUMBER"
  - git push "https://${GITHUB_TOKEN}@github.com/LexSwed/use-pipe.git" HEAD:master